# Generated by Django 4.1 on 2022-09-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMundial', '0002_remove_partidos_resutlado_partidos_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='resultado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
